version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: vue_app
    environment:
      - VIRTUAL_HOST=summarizerai.online
      - LETSENCRYPT_HOST=summarizerai.online
      - LETSENCRYPT_EMAIL=your-email@summarizerai.online
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    container_name: flask_api
    volumes:
      - ./backend:/flask_app
      - ./secrets:/run/secrets:ro
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres
      - VIRTUAL_HOST=api.summarizerai.online
      - LETSENCRYPT_HOST=api.summarizerai.online
      - LETSENCRYPT_EMAIL=your-email@summarizerai.online
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=summarizerai-test
      - MAX_FILE_SIZE_MB=2
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - MAX_SUMMARIES_PER_MONTH=500
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - FRONT_END_PASSWORD_RESET_PAGE_URL=${FRONT_END_PASSWORD_RESET_PAGE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info --pool=solo
    volumes:
      - ./backend:/app
      - ./secrets:/run/secrets:ro
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - MAX_FILE_SIZE_MB=2
    depends_on:
      - backend
      - redis
      - db
    restart: always
    stdin_open: true
    tty: true

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  postgres_data:
