version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs # 🔁 FIXED: was read-only; must be read-write
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge # 🔁 Ensure challenge dir is properly mapped
    networks:
      - webproxy # 🔁 Add to shared network
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx_proxy
      # Optional for testing:
      # - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge
    depends_on:
      - nginx-proxy
    networks:
      - webproxy
    restart: always

  frontend:
    build: ./frontend
    container_name: vue_app
    environment:
      - VIRTUAL_HOST=summarizerai.online,www.summarizerai.online
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=summarizerai.online,www.summarizerai.online
      - LETSENCRYPT_EMAIL=your-email@summarizerai.online
    networks:
      - webproxy
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: flask_api
    volumes:
      - ./backend:/flask_app
      - ./secrets:/run/secrets:ro
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres
      - VIRTUAL_HOST=api.summarizerai.online
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.summarizerai.online
      - LETSENCRYPT_EMAIL=your-email@summarizerai.online
      - AWS_REGION=us-east-2
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=summarizerai
      - MAX_FILE_SIZE_MB=2
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - MAX_SUMMARIES_PER_MONTH=500
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - FRONT_END_PASSWORD_RESET_PAGE_URL=${FRONT_END_PASSWORD_RESET_PAGE_URL}
    networks:
      - webproxy
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./secrets:/run/secrets:ro
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - OPEN_API_KEY=${OPEN_API_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - MAX_FILE_SIZE_MB=2
    depends_on:
      - backend
      - redis
      - db
    networks:
      - webproxy
    restart: always
    stdin_open: true
    tty: true

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

volumes:
  postgres_data:

networks:
  webproxy:
